# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check CI

on:
  push:
    branches: ["**"]

jobs:
  build:
    if: ${{ false }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: borales/actions-yarn@v4
      with:
        cmd: install

    - name: Format with prettier
      uses: borales/actions-yarn@v4
      with:
        cmd: format

    - name: Build code
      uses: borales/actions-yarn@v4
      with:
        cmd: build
